export const FETCH_LANGUAGES = 'FETCH_LANGUAGES';
export const FETCH_PROJECTS = 'FETCH_PROJECTS';
export const FETCH_PROJECT = 'FETCH_PROJECT';
export const FETCH_PROJECTS_BY_LANGUAGE = 'FETCH_PROJECTS_BY_LANGUAGE';
